# tasks file
---
- name: install dependencies  # noqa args[module]
  ansible.builtin.apt:
    name: "{{ memtier_benchmark_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-dependencies

- name: create (checkout) directory
  ansible.builtin.file:
    path: /var/lib/ansible/memtier-benchmark/checkouts
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-checkout

- name: checkout repository
  ansible.builtin.git:
    repo: https://github.com/RedisLabs/memtier_benchmark.git
    dest: "{{ memtier_benchmark_checkout_path }}"
    version: "{{ memtier_benchmark_version }}"
    force: true
  register: _git_checkout
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-checkout

- name: build and install
  ansible.builtin.shell: >
    autoreconf -ivf && ./configure && make && make install
  args:
    chdir: "{{ memtier_benchmark_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-build-and-install

- name: cleanup build
  ansible.builtin.shell: >
    git reset --hard && git clean -d -x -f
  args:
    chdir: "{{ memtier_benchmark_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-cleanup-build
