# tasks file for memtier-benchmark
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: memtier_benchmark_dependencies
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-dependencies

- name: create (checkout) directory
  file:
    path: /var/lib/ansible/memtier-benchmark/checkouts
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-checkout

- name: checkout repository
  git:
    repo: https://github.com/RedisLabs/memtier_benchmark.git
    dest: "/var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark"
    version: "{{ memtier_benchmark_version }}"
  register: result
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-checkout

#- name: build deb file
#  shell: "/var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark/mkdeb.sh && mv /var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark/memtier-benchmark-{{ memtier-benchmark_version }}_{{ ansible_machine }}.deb /var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark-{{ memtier-benchmark_version }}_{{ ansible_machine }}.deb"
#  args:
#    chdir: "/var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark"
#    creates: "/var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark-{{ memtier-benchmark_version }}_{{ ansible_machine }}.deb"
#  tags:
#    - configuration
#    - memtier-benchmark
#    - memtier-benchmark-build-deb
#
#- name: install deb file
#  apt:
#    deb: "/var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark-{{ memtier-benchmark_version }}_{{ ansible_machine }}.deb"
#  tags:
#    - configuration
#    - memtier-benchmark
#    - memtier-benchmark-install-deb

- name: cleanup build
  shell: "git reset --hard && git clean -d -x -f"
  args:
    chdir: "/var/lib/ansible/memtier-benchmark/checkouts/memtier-benchmark"
  when: result | changed
  tags:
    - configuration
    - memtier-benchmark
    - memtier-benchmark-cleanup-build
